apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keda

labels:
  - includeSelectors: true
    pairs:
      org: cision-devops
  - pairs:
      businessunit: integrated
      organization: cision-devops
      owner: devops
      product: devops
      repo: keda

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: keda
    namespace: keda
    releaseName: keda
    valuesFile: keda-values.yaml
