name: keda-test
on: push
jobs:
  kind-tests:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, small] # no cgroupsv2 yet.
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: get node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install task
        run: npm install -g @go-task/cli
      - name: run tests
        run: task full-test
